version: '3.1'

services:
  webserver:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: webserver
    ports:
      - 80:80
    volumes:
      - .:/opt/mps/cms/solution/www
      - ./logs/apache2:/var/log/apache2

  db:
    image: mysql:5.5
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${mysqlpassword}
      - MYSQL_DATABASE=${mysql_db}
      - MYSQL_USER=${mysqluser}
      - MYSQL_PASSWORD=${mysqlpassword}
    ports:
      - 3306:3306
    volumes:
      - /var/lib/mysql/${mysql_db}:/var/lib/mysql/${mysql_db}
