version: '3.1'

services:
  webserver:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: webserver
    ports:
      - 80:80
    volumes:
      - ${SOLUTION_DIR}/www
      - ${SOLUTION_DIR}/logs/apache2:/var/log/apache2

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./db_data:/var/lib/mysql/data
  